package me.frauenfelderflorian.tournamentscompose.common.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF006D42)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF93F7BC)
val light_onPrimaryContainer = Color(0xFF002111)
val light_secondary = Color(0xFF4E6355)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD1E8D6)
val light_onSecondaryContainer = Color(0xFF0C1F14)
val light_tertiary = Color(0xFF3B6471)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFBFE9F8)
val light_onTertiaryContainer = Color(0xFF001F27)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFBFDF8)
val light_onBackground = Color(0xFF191C1A)
val light_surface = Color(0xFFFBFDF8)
val light_onSurface = Color(0xFF191C1A)
val light_surfaceVariant = Color(0xFFDCE5DC)
val light_onSurfaceVariant = Color(0xFF404942)
val light_outline = Color(0xFF717972)
val light_inverseOnSurface = Color(0xFFF0F1ED)
val light_inverseSurface = Color(0xFF2E312E)
val light_inversePrimary = Color(0xFF77DAA1)
val light_surfaceTint = Color(0xFF006D42)
val light_outlineVariant = Color(0xFFC0C9C0)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFF77DAA1)
val dark_onPrimary = Color(0xFF003920)
val dark_primaryContainer = Color(0xFF005231)
val dark_onPrimaryContainer = Color(0xFF93F7BC)
val dark_secondary = Color(0xFFB5CCBA)
val dark_onSecondary = Color(0xFF213528)
val dark_secondaryContainer = Color(0xFF374B3E)
val dark_onSecondaryContainer = Color(0xFFD1E8D6)
val dark_tertiary = Color(0xFFA3CDDC)
val dark_onTertiary = Color(0xFF033541)
val dark_tertiaryContainer = Color(0xFF224C58)
val dark_onTertiaryContainer = Color(0xFFBFE9F8)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF191C1A)
val dark_onBackground = Color(0xFFE1E3DE)
val dark_surface = Color(0xFF191C1A)
val dark_onSurface = Color(0xFFE1E3DE)
val dark_surfaceVariant = Color(0xFF404942)
val dark_onSurfaceVariant = Color(0xFFC0C9C0)
val dark_outline = Color(0xFF8A938B)
val dark_inverseOnSurface = Color(0xFF191C1A)
val dark_inverseSurface = Color(0xFFE1E3DE)
val dark_inversePrimary = Color(0xFF006D42)
val dark_surfaceTint = Color(0xFF77DAA1)
val dark_outlineVariant = Color(0xFF404942)
val dark_scrim = Color(0xFF000000)

val seed = Color(0xFF339966)

val LightColors = lightColorScheme(
    primary = light_primary,
    onPrimary = light_onPrimary,
    primaryContainer = light_primaryContainer,
    onPrimaryContainer = light_onPrimaryContainer,
    secondary = light_secondary,
    onSecondary = light_onSecondary,
    secondaryContainer = light_secondaryContainer,
    onSecondaryContainer = light_onSecondaryContainer,
    tertiary = light_tertiary,
    onTertiary = light_onTertiary,
    tertiaryContainer = light_tertiaryContainer,
    onTertiaryContainer = light_onTertiaryContainer,
    error = light_error,
    errorContainer = light_errorContainer,
    onError = light_onError,
    onErrorContainer = light_onErrorContainer,
    background = light_background,
    onBackground = light_onBackground,
    surface = light_surface,
    onSurface = light_onSurface,
    surfaceVariant = light_surfaceVariant,
    onSurfaceVariant = light_onSurfaceVariant,
    outline = light_outline,
    inverseOnSurface = light_inverseOnSurface,
    inverseSurface = light_inverseSurface,
    inversePrimary = light_inversePrimary,
    surfaceTint = light_surfaceTint,
    outlineVariant = light_outlineVariant,
    scrim = light_scrim,
)
val DarkColors = darkColorScheme(
    primary = dark_primary,
    onPrimary = dark_onPrimary,
    primaryContainer = dark_primaryContainer,
    onPrimaryContainer = dark_onPrimaryContainer,
    secondary = dark_secondary,
    onSecondary = dark_onSecondary,
    secondaryContainer = dark_secondaryContainer,
    onSecondaryContainer = dark_onSecondaryContainer,
    tertiary = dark_tertiary,
    onTertiary = dark_onTertiary,
    tertiaryContainer = dark_tertiaryContainer,
    onTertiaryContainer = dark_onTertiaryContainer,
    error = dark_error,
    errorContainer = dark_errorContainer,
    onError = dark_onError,
    onErrorContainer = dark_onErrorContainer,
    background = dark_background,
    onBackground = dark_onBackground,
    surface = dark_surface,
    onSurface = dark_onSurface,
    surfaceVariant = dark_surfaceVariant,
    onSurfaceVariant = dark_onSurfaceVariant,
    outline = dark_outline,
    inverseOnSurface = dark_inverseOnSurface,
    inverseSurface = dark_inverseSurface,
    inversePrimary = dark_inversePrimary,
    surfaceTint = dark_surfaceTint,
    outlineVariant = dark_outlineVariant,
    scrim = dark_scrim,
)
